/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comdiegocano_mentiroso_Carta */

#ifndef _Included_comdiegocano_mentiroso_Carta
#define _Included_comdiegocano_mentiroso_Carta
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comdiegocano_mentiroso_Carta
 * Method:    compararCarta
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_comdiegocano_mentiroso_Carta_compararCarta
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
