/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comdiegocano_mentiroso_Jugador */

#ifndef _Included_comdiegocano_mentiroso_Jugador
#define _Included_comdiegocano_mentiroso_Jugador
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comdiegocano_mentiroso_Jugador
 * Method:    agregarPunto
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Jugador_agregarPunto
  (JNIEnv *, jobject);

/*
 * Class:     comdiegocano_mentiroso_Jugador
 * Method:    quitarPunto
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Jugador_quitarPunto
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
