/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comdiegocano_mentiroso_Jugador */

#ifndef _Included_comdiegocano_mentiroso_Jugador
#define _Included_comdiegocano_mentiroso_Jugador
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comdiegocano_mentiroso_Jugador
 * Method:    agregarPuntos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Jugador_agregarPuntos
  (JNIEnv *, jobject, jint);

/*
 * Class:     comdiegocano_mentiroso_Jugador
 * Method:    quitarPuntos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Jugador_quitarPuntos
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
