/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comdiegocano_mentiroso_Baraja */

#ifndef _Included_comdiegocano_mentiroso_Baraja
#define _Included_comdiegocano_mentiroso_Baraja
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comdiegocano_mentiroso_Baraja
 * Method:    barajar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Baraja_barajar
  (JNIEnv *, jobject);

/*
 * Class:     comdiegocano_mentiroso_Baraja
 * Method:    eliminarCarta
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Baraja_eliminarCarta
  (JNIEnv *, jobject, jint);

/*
 * Class:     comdiegocano_mentiroso_Baraja
 * Method:    agregarCarta
 * Signature: (Lcomdiegocano/mentiroso/Carta;)V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Baraja_agregarCarta
  (JNIEnv *, jobject, jobject);

/*
 * Class:     comdiegocano_mentiroso_Baraja
 * Method:    vaciarBaraja
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Baraja_vaciarBaraja
  (JNIEnv *, jobject);

/*
 * Class:     comdiegocano_mentiroso_Baraja
 * Method:    tamanoBaraja
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_comdiegocano_mentiroso_Baraja_tamanoBaraja
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
