/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comdiegocano_mentiroso_Juego */

#ifndef _Included_comdiegocano_mentiroso_Juego
#define _Included_comdiegocano_mentiroso_Juego
#ifdef __cplusplus
extern "C" {
#endif
#undef comdiegocano_mentiroso_Juego_FOCUS_TRAVERSABLE_UNKNOWN
#define comdiegocano_mentiroso_Juego_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef comdiegocano_mentiroso_Juego_FOCUS_TRAVERSABLE_DEFAULT
#define comdiegocano_mentiroso_Juego_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef comdiegocano_mentiroso_Juego_FOCUS_TRAVERSABLE_SET
#define comdiegocano_mentiroso_Juego_FOCUS_TRAVERSABLE_SET 2L
#undef comdiegocano_mentiroso_Juego_TOP_ALIGNMENT
#define comdiegocano_mentiroso_Juego_TOP_ALIGNMENT 0.0f
#undef comdiegocano_mentiroso_Juego_CENTER_ALIGNMENT
#define comdiegocano_mentiroso_Juego_CENTER_ALIGNMENT 0.5f
#undef comdiegocano_mentiroso_Juego_BOTTOM_ALIGNMENT
#define comdiegocano_mentiroso_Juego_BOTTOM_ALIGNMENT 1.0f
#undef comdiegocano_mentiroso_Juego_LEFT_ALIGNMENT
#define comdiegocano_mentiroso_Juego_LEFT_ALIGNMENT 0.0f
#undef comdiegocano_mentiroso_Juego_RIGHT_ALIGNMENT
#define comdiegocano_mentiroso_Juego_RIGHT_ALIGNMENT 1.0f
#undef comdiegocano_mentiroso_Juego_serialVersionUID
#define comdiegocano_mentiroso_Juego_serialVersionUID -7644114512714619750i64
#undef comdiegocano_mentiroso_Juego_serialVersionUID
#define comdiegocano_mentiroso_Juego_serialVersionUID 4613797578919906343i64
#undef comdiegocano_mentiroso_Juego_INCLUDE_SELF
#define comdiegocano_mentiroso_Juego_INCLUDE_SELF 1L
#undef comdiegocano_mentiroso_Juego_SEARCH_HEAVYWEIGHTS
#define comdiegocano_mentiroso_Juego_SEARCH_HEAVYWEIGHTS 1L
#undef comdiegocano_mentiroso_Juego_OPENED
#define comdiegocano_mentiroso_Juego_OPENED 1L
#undef comdiegocano_mentiroso_Juego_serialVersionUID
#define comdiegocano_mentiroso_Juego_serialVersionUID 4497834738069338734i64
#undef comdiegocano_mentiroso_Juego_DEFAULT_CURSOR
#define comdiegocano_mentiroso_Juego_DEFAULT_CURSOR 0L
#undef comdiegocano_mentiroso_Juego_CROSSHAIR_CURSOR
#define comdiegocano_mentiroso_Juego_CROSSHAIR_CURSOR 1L
#undef comdiegocano_mentiroso_Juego_TEXT_CURSOR
#define comdiegocano_mentiroso_Juego_TEXT_CURSOR 2L
#undef comdiegocano_mentiroso_Juego_WAIT_CURSOR
#define comdiegocano_mentiroso_Juego_WAIT_CURSOR 3L
#undef comdiegocano_mentiroso_Juego_SW_RESIZE_CURSOR
#define comdiegocano_mentiroso_Juego_SW_RESIZE_CURSOR 4L
#undef comdiegocano_mentiroso_Juego_SE_RESIZE_CURSOR
#define comdiegocano_mentiroso_Juego_SE_RESIZE_CURSOR 5L
#undef comdiegocano_mentiroso_Juego_NW_RESIZE_CURSOR
#define comdiegocano_mentiroso_Juego_NW_RESIZE_CURSOR 6L
#undef comdiegocano_mentiroso_Juego_NE_RESIZE_CURSOR
#define comdiegocano_mentiroso_Juego_NE_RESIZE_CURSOR 7L
#undef comdiegocano_mentiroso_Juego_N_RESIZE_CURSOR
#define comdiegocano_mentiroso_Juego_N_RESIZE_CURSOR 8L
#undef comdiegocano_mentiroso_Juego_S_RESIZE_CURSOR
#define comdiegocano_mentiroso_Juego_S_RESIZE_CURSOR 9L
#undef comdiegocano_mentiroso_Juego_W_RESIZE_CURSOR
#define comdiegocano_mentiroso_Juego_W_RESIZE_CURSOR 10L
#undef comdiegocano_mentiroso_Juego_E_RESIZE_CURSOR
#define comdiegocano_mentiroso_Juego_E_RESIZE_CURSOR 11L
#undef comdiegocano_mentiroso_Juego_HAND_CURSOR
#define comdiegocano_mentiroso_Juego_HAND_CURSOR 12L
#undef comdiegocano_mentiroso_Juego_MOVE_CURSOR
#define comdiegocano_mentiroso_Juego_MOVE_CURSOR 13L
#undef comdiegocano_mentiroso_Juego_NORMAL
#define comdiegocano_mentiroso_Juego_NORMAL 0L
#undef comdiegocano_mentiroso_Juego_ICONIFIED
#define comdiegocano_mentiroso_Juego_ICONIFIED 1L
#undef comdiegocano_mentiroso_Juego_MAXIMIZED_HORIZ
#define comdiegocano_mentiroso_Juego_MAXIMIZED_HORIZ 2L
#undef comdiegocano_mentiroso_Juego_MAXIMIZED_VERT
#define comdiegocano_mentiroso_Juego_MAXIMIZED_VERT 4L
#undef comdiegocano_mentiroso_Juego_MAXIMIZED_BOTH
#define comdiegocano_mentiroso_Juego_MAXIMIZED_BOTH 6L
#undef comdiegocano_mentiroso_Juego_serialVersionUID
#define comdiegocano_mentiroso_Juego_serialVersionUID 2673458971256075116i64
/*
 * Class:     comdiegocano_mentiroso_Juego
 * Method:    cambiarTurno
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Juego_cambiarTurno
  (JNIEnv *, jobject);

/*
 * Class:     comdiegocano_mentiroso_Juego
 * Method:    incrementarRonda
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_comdiegocano_mentiroso_Juego_incrementarRonda
  (JNIEnv *, jobject);

/*
 * Class:     comdiegocano_mentiroso_Juego
 * Method:    esGanadorJuego
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_comdiegocano_mentiroso_Juego_esGanadorJuego
  (JNIEnv *, jobject, jint);

/*
 * Class:     comdiegocano_mentiroso_Juego
 * Method:    obtenerTurnoAnterior
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_comdiegocano_mentiroso_Juego_obtenerTurnoAnterior
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
